# Generated by Django 3.0.8 on 2020-07-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='profile.png', upload_to='profile_photo/'),
        ),
    ]
