# Generated by Django 3.0.8 on 2020-07-08 11:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0002_auto_20200708_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1594203074/profile_saedp5.png', max_length=255, verbose_name='profile_photo'),
        ),
    ]
