# Generated by Django 3.0.8 on 2020-07-06 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0004_auto_20200706_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snaps.Profile'),
        ),
    ]
