# Generated by Django 3.0.8 on 2020-07-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0005_auto_20200706_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
