# Generated by Django 3.0.8 on 2020-07-06 02:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0006_auto_20200706_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='snaps.Profile'),
            preserve_default=False,
        ),
    ]
