# Generated by Django 3.0.8 on 2020-07-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0012_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
