# Generated by Django 3.0.8 on 2020-07-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0014_auto_20200706_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
