# Generated by Django 3.0.8 on 2020-07-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0019_auto_20200706_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
