# Generated by Django 3.0.8 on 2020-07-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0021_auto_20200706_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
